bazel_dep(name = "rules_go", version = "0.52.0")
bazel_dep(name = "gazelle", version = "0.40.0")
bazel_dep(name = "toolchains_llvm_bootstrapped", version = "")

local_path_override(
    module_name = "toolchains_llvm_bootstrapped",
    path = "../../",
)

register_toolchains(
    "@toolchains_llvm_bootstrapped//toolchain:all",
)

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.23.4")
use_repo(go_sdk, "go_toolchains")

register_toolchains("@go_toolchains//:all")
